name: Book Build & Deploy
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        
        strategy:
            matrix:
                python-version: [3.10]
        steps:
            - uses: actions/checkout@v4
            - name: Use Python ${{ matrix.node-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Compile & Build Book
              run: |
                  python scripts/create_html.py

            - name: Commit build to gp-python
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git --work-tree dist add --all 
                  git commit -m "Python deployment run by github-actions"
                  git push origin HEAD:gp-python --force
              shell: bash
